version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8080:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        build: ./mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: mbhaya
            MYSQL_PASSWORD: trewq
            MYSQL_ROOT_PASSWORD: trewq
volumes:
    persistent:
